### PR TITLE
sm3 initial implementation

### LINKED ISSUE #10: Implement the SM3 algorithm
See paper:
https://arxiv.org/abs/1901.11150

### PR DESCRIPTION
**Pull request by joaogui1**
Closes #10 
My implementation is based on [jax.experimental.optim](https://jax.readthedocs.io/en/latest/_modules/jax/experimental/optimizers.html#sm3) implementation.
Still need to: 

- [x] Add documentation
- [x] Add & run tests

Any feedback/review is appreciated!

### CODE REVIEW

**Comment by mtthss** [comment]
This looks great!
Could you add tests?

**Comment by mtthss** [comment]
An equivalence test comparing to experimental.optimizers would also be nice since your implementation is based on that

**Comment by joaogui1** [comment]
I added the documentation, but right now the transform doesn't run, it errors with:
```python
TypeError: list indices must be integers or slices, not DynamicJaxprTracer
```
Caused by the splice function. Any idea how to fix it @mtthss ?

**Comment by mtthss** [comment]
It seems like in `splice` you are trying to index into a python list with the dynamic content of a jax array.

**Comment by joaogui1** [comment]
Hey @mtthss it's now passing the tests and I added the docstring :D

**Comment by mtthss** [comment]
Awesome! Could you just add also an equivalence test in `equivalence_test.py` verifying equivalence to `jax.experimental.optiimizer`'s version?

**Comment by mtthss** [comment]
Also there seem to be some lint errors in Github presebmit checkx

**Comment by mtthss** [comment]
Hello! Would be great to merge this!
Could you fix the lint errors and resolve conflicts?

**Comment by joaogui1** [comment]
Sorry about being so slow, I'm doing an internship right now and don't have as much time as I used to, is it ok for me to fix this tomorrow morning?

**Comment by mtthss** [comment]
Of course! Whenever works for you!
Your contributions are much appreciated!

**Comment by joaogui1** [comment]
My version fails with general pytrees, I need to run that max operation for each vector in the pytree, though I'm not sure how to do it (it would be like stopping the tree_map right before the leaves)

**Comment by mtthss** [comment]
Shouldn't the jax.experimental.optimizers also have solved the same issue already?
Can we follow the same approach as them?

**Comment by joaogui1** [comment]
So @mtthss I spoke with Rohan Anil (one of the authors) and he explained to me the shape magic they do and now the optimizer is passing all tests and is more complete than the jax.optimizers version \o/

**Review by mtthss — APPROVED** [review]

**Comment by mtthss** [comment]
This was great, thanks a lot for the contribution!

**Comment by 8bitmp3** [comment]
This is awesome @joaogui1 

@mtthss I can expand the sm3 description based on https://arxiv.org/pdf/1901.11150.pdf after this PR is merged 👍

**Comment by mtthss** [comment]
Thanks @joaogui1 for the great contribution, this is now merged!
@8bitmp3 if you take expanding the description that would be great thx!

**Pull request merged**
