### PR TITLE
Create .gitignore

### PR DESCRIPTION
**Pull request by NeilGirdhar**
Based on JAX's gitignore

### CODE REVIEW

**Comment by hbq1** [comment]
Hey Neil, thanks for the contribution.

Yeah I think we can safely remove those entries since Optax does not rely on Bazel/TF etc.

**Comment by mtthss** [comment]
If you can remove those entries we can then merge the PR.
Apologies for the delay in getting back to you.

**Comment by NeilGirdhar** [comment]
Done as requested :)

**Review by hbq1 — APPROVED** [review]

**Comment by joaogui1** [comment]
Hey @NeilGirdhar @hbq1 what's the state of this PR? Having a gitignore sure helps :)

**Comment by NeilGirdhar** [comment]
It should be ready to check in right?  Unless you want me to rebase onto master?

**Comment by hbq1** [comment]
Apologies for the delay! Merged now.

**Pull request merged**
