### PR TITLE
change int64 to int32 to avoid warnings

### PR DESCRIPTION
**Pull request by rdaems**
I have some annoying warnings because the int64 are converted to int32 on my GPU.
They can easily be avoided by changing the dtypes to int32 (which is quite sufficient).

### CODE REVIEW

**Review by mkunesch — CHANGES_REQUESTED** [review]
Hi! Thanks a lot for pointing this out and filing a PR!

For completeness and for others who are seeing this, I think the warning you are referring to is:
```
UserWarning: Explicitly requested dtype <class 'jax._src.numpy.lax_numpy.int64'> requested in zeros is not available, and will be truncated to dtype int32.
```
This warning should only appear the first time a jit compiled function is called.

We have to be a bit careful with this change I think because there are models that are trained for long enough to exceed 2^31 steps. Having said this, all other parts of optax use (safely incremented) int32s so I think it makes sense to bring the wrappers in line.

Could you modify the PR to use `numerics.safe_int32_increment` for all the counters you have changed to int32? This ensures that users don't get completely surprising behaviour due to a negative step count.

**Comment by rdaems** [comment]
I hope I did it right now, I changed all `+1` occurences with `safe_int32_increment`.
All tests are ok. And I fetched upstream.

Now I do have errors when I use the faulty dtype. It seems everything is covered.

**Review by mkunesch — CHANGES_REQUESTED** [review]
Hi @rdaems! Thanks a lot for making the changes - this looks great! I have found one more place where a safe increment should be used (total_notfinite wasn't yet incremented safely). Could you add it there too?

Thanks a lot again for raising this! The change doesn't only get rid of warning, it also makes the code safer: previously if int64 wasn't supported, users would get int32 with unsafe increments that might lead to negative numbers. It's good to change this to guarantee "safe" increments on all architectures.

**Comment by mkunesch** [comment]
Btw: this is a small change so I'd be happy to approve the PR and patch the change in myself as it is merged. Let me know whether that's okay for you :-)! Thanks a lot again!

**Comment by rdaems** [comment]
Hi @mkunesch 
Sorry for my slow response. I hope I did that last one correct.

Nice to hear that the change also makes the code safer!

**Review by mkunesch — APPROVED** [review]
Looks great! Thank you very much!

**Pull request merged**
