### PR TITLE
Radam

### LINKED ISSUE #8: Implement rectified Adam
See paper:

https://arxiv.org/abs/1908.03265

### PR DESCRIPTION
**Pull request by joaogui1**
Closes #8 
Couple things:

1. My implementation with `cond` seems hackish, any tips?
2. The paper uses 4 as threshold, but the official implementation uses 5, which value should we use?
3. It's passing parabel but failing rosenbrock (with a divergence), I will check it out on Monday
4. Any other feedback on the implementation is welcome!

### CODE REVIEW

**Comment by joaogui1** [comment]
You know what, I don't like this implementation, it needs to be more modular (like the AdamW weight scaling). I will try to fix it and then ping you when it's better or I need some help

**Comment by joaogui1** [comment]
So, this version almost works, except that if `ro >= threshold` we should return the SGD+momentum updates, not Adam's update, any idea how we could reverse Adam's adaptive stuff? Or do you prefer the original version where there's a `scale_by_radam` transform?  
```python
def rectify(b2: float = 0.999,      
                threshold: float = 5.0) -> GradientTransformation:
  """..."""

  ro_inf = 2./(1 - b2) - 1
  def _radam_update(args):
    ro = args[0]
    updates = args[1]
    r = jnp.sqrt((ro - 4)*(ro - 2)*ro_inf/((ro_inf - 4)*(ro_inf - 2)*ro))
    updates = jax.tree_map(lambda g: r*g , updates)
    return updates

  def init_fn(params):
    return RectifyState(b2t=b2, count=jnp.zeros([], jnp.int32))

  def update_fn(updates, state, params=None):
    del params
    count_inc = _safe_int32_increment(state.count)
    b2t = state.b2t
    b2t *= b2
    ro = ro_inf - 2*count_inc*b2t/(1 - b2t)
    updates = jax.lax.cond(ro >= threshold, _radam_update, lambda _: updates,
                    (ro, updates))
    return updates, RectifyState(b2t=b2t, count=count_inc)

  return GradientTransformation(init_fn, update_fn)

```

**Comment by mtthss** [comment]
I like the idea of this being decoupled from the standard Adam part similarly to adamw, however I am struggling to see the right way to achieve it. As you mentioned we would need to invert Adam when not entering the branch which differently from weight decay is something that only makes sense if you are following Adam. Therefore the split wouldn't *really* allow you to freely compose it anyway. In which case I would be inclined to go with the first version

**Comment by joaogui1** [comment]
I think I've implemented it correctly, but I'm getting a divergence in the rosebrock test, any idea what could be causing it?

**Comment by mtthss** [comment]
I can't spot anything obviously wrong? By divergence do you mean literal divergence to infinity?

**Comment by joaogui1** [comment]
Well, looks pretty big to me
```python
FAIL: test_rosenbrock_radam (__main__.AliasTest)
...
AssertionError: 
Not equal to tolerance rtol=0.03, atol=0.03
Error in value equality check: Values not approximately equal
Mismatched elements: 2 / 2 (100%)
Max absolute difference: 3069795.5
Max relative difference: 3069795.5
 x: array([3069796.5  ,   23477.021], dtype=float32)
 y: array([1., 1.], dtype=float32)
```

**Comment by mtthss** [comment]
Mmm yeah that is pretty bad indeed :(

**Comment by mtthss** [comment]
Maybe you could compare the output of a single step of your radam implementation to some canonical radam implementation (even in another framework)?

**Comment by joaogui1** [comment]
Hey @mtthss I changed the learning rate to match the common learning rate in TF-addons and now it passes. Think that's enough?

**Comment by joaogui1** [comment]
Ok, the last message was lazy on my part, here's a [colab](https://colab.research.google.com/drive/10yXn4fKNSenkx4k8RQAGtMhZFW4BkUh3?usp=sharing) comparing my implementation and Tenforflow Addon's

1. The results are very similar in the first 10-step test with 1e-1 learning rate
2. Both converge with 1e-3 lr and 10000 steps.

**Comment by joaogui1** [comment]
So @mtthss, what do you think?

**Review by mtthss — APPROVED** [review]

**Comment by mtthss** [comment]
Looks good! I'll merge!
Thank you a lot for your contribution!

**Comment by carlosgmartin** [comment]
What's the recommended way to use weight decay with [`radam`](https://optax.readthedocs.io/en/latest/api.html#optax.radam), since it doesn't have a `weight_decay` argument like [`adamw`](https://optax.readthedocs.io/en/latest/api.html#optax.adamw) does? `optax.chain(optax.add_decayed_weights(weight_decay), optax.radam(lr))`?

**Pull request merged**
