### PR TITLE
Add Optax regression flax_example.py

### PR DESCRIPTION
**Pull request by 8bitmp3**
Quick adaptation from https://flax.readthedocs.io/en/latest/notebooks/flax_basics.html cc @avital @marcvanzee @levskaya

### CODE REVIEW

**Comment by mtthss** [comment]
Looks good to me!

**Comment by andsteing** [comment]
Is this forked from one of the other Optax examples? If so, could you mention the PR (and maybe even in the source file)?

**Comment by 8bitmp3** [comment]
@andsteing I think it's the initial commit https://github.com/deepmind/optax/commit/d0ba208a300d68a3f4e380ed2a0b70848380988b#diff-c590b3c924c35c2f241746522284e4709df490d73a38aaa7d6de4ed1eac2f546 - custom Adam is from haiku_example

**Comment by 8bitmp3** [comment]
let me know if you need me to change anything here @andsteing @mtthss

**Comment by andsteing** [comment]
LGTM. Note that @mtthss is OOO for a bit, you might want to add another Optax maintainer to get the PR approved... Maybe @fabioviola ?

**Review by GregCT — APPROVED** [review]

**Pull request merged**
